# Generated by Django 4.2.7 on 2024-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assistant_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="thread_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
