# Generated by Django 4.2.7 on 2024-04-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="OrganizationFile",
        ),
    ]
