# Generated by Django 4.2.7 on 2024-04-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_session_sessionchathistory_delete_chathistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionchathistory",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_history",
                to="chat.session",
            ),
        ),
    ]
