# Generated by Django 4.2.7 on 2024-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_sessionchathistory_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="thread_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
