# Generated by Django 4.2.7 on 2024-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_assistant"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="instructions",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assistant",
            name="model",
            field=models.CharField(default="gpt-4-turbo", max_length=100),
        ),
        migrations.AddField(
            model_name="assistant",
            name="name",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assistant",
            name="vector_store_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
