# Generated by Django 4.2.7 on 2024-04-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_organizationfile_file"),
        ("chat", "0008_assistant_instructions_assistant_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.organizationfile",
            ),
        ),
    ]
