# Generated by Django 4.2.7 on 2024-04-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_remove_assistant_vector_store_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assitantvectorstore",
            name="assistant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vectorstore",
                to="chat.assistant",
            ),
        ),
    ]
