# Generated by Django 4.2.7 on 2024-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_remove_session_thread_id_alter_session_user_thread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="thread_id",
            field=models.CharField(max_length=30),
        ),
    ]
