# Generated by Django 4.2.7 on 2024-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_thread_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="thread_id",
            field=models.CharField(max_length=100),
        ),
    ]
